### PR TITLE
Add Saturation Arithmetic Intrinsics

### PR DESCRIPTION
**Pull request by baziotis**
Solving issue: https://github.com/ldc-developers/ldc/issues/2925

### CODE REVIEW

**Comment by kinke** [comment]
Thx. These intrinsics have apparently been added with LLVM 8 (not present in http://releases.llvm.org/7.0.0/docs/LangRef.html, but in http://releases.llvm.org/8.0.0/docs/LangRef.html), so please guard with `version (INTRINSICS_FROM_800)`.

**Comment by baziotis** [comment]
Done, I don't know how you prefer the indentation though.

**Comment by thewilsonator** [comment]
D files in [the D style](https://dlang.org/dstyle.html), C++ in the LLVM style.

**Comment by baziotis** [comment]
Yes, but I've seen `version` in different flavors. From what I see, I think it's ok (i.e. the other `version (INTRINSICS...)` follow the same indentation.

**Pull request merged**
