### PR TITLE
[Trivial] Backport dlang_druntime PR 2161

### PR DESCRIPTION
**Pull request by dkgroot**
Backport dlang druntime [PR2161](https://github.com/dlang/druntime/pull/2161)
Platform: DragonFlyBSD

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Looks like this is needed for 2.080. But waiting with merge until after merge-2.080 branch merge. (I'm guessing it may result in merge conflicts in that branch)

**Comment by dkgroot** [comment]
Ooh ok, i was not sure if this needed to be back ported to 1.9.0 or if it would just have to wait to the next release. Thanks for resolving that.

**Comment by dkgroot** [comment]
You can close this one, if you are going to wait for 2.080 (It already contains this). I thought it might have to be backported to v1.9.0 (I wasn't clear on how dlang druntime and phobos is being tracked)

**Comment by JohanEngelen** [comment]
v1.9.x is dlang 2.079. For a given "x.y.*" version series, we don't change frontend/phobos/druntime version. "y" is increased when the dlang version is increased (or when we feel like it).

**Pull request closed without merging**
