### PR TITLE
full MSVCRT support in core.stdc.math and core.stdc.tgmath; add new LLVM 3.3 intrinsics

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by redstar** [comment]
Hi Martin! Thanks for your great work. It is really nice to see progress in this area. :-)

I noted that you made a druntime pull request, too. In order to minimize the review effort (e.g. I don't know anything about FreeBSD) I will wait for the upstream changes. (I re-start merging upstream changes as soon as the 2.061 merge is done.)

Nevertheless I am going to cherry-pick the LDC-specific parts (llvm.intrinsics, ldc.longdouble) because I think it is nice to have these changes.

Again, thanks for the pull request.

**Comment by kinke** [comment]
Hi redstar, you're welcome! Thanks for your hard work. I was surprised I could get LDC quite painlessly to compile and kind of work ;) on Win64, in contrast to GDC with MingGW64. I really like LDC's MSVCRT runtime dependency shared with DMD on Win64, so most things already work. So I guess LDC is the future for D on the Windows platform.
The assembler implementations in Phobos' std.math don't work (at least most of them), so unfortunately many DMD Win64 work-arounds for MSVCRT's missing C99 math support do not work for LDC. Could you please provide some insight as to what the current problems with inline assembly are?

**Comment by redstar** [comment]
I committed the `ldc.intrinsics` and `core.math` stuff.

Regarding the assembler there is simply a bug which prevents some of the instructions to be assembled.

**Comment by kinke** [comment]
Do you have any more details regarding this bug, or could you please point me to the related source files? I'd like to help, although I don't know anything about LLVM. :)

**Comment by redstar** [comment]
The assembler part of LDC parses the instructions in DMD asm {} syntax and rewrites them in LLVM syntax. Known problems are:
- several instructions are missing (e.g. lot of SSSE3/SSE4) or the operand definition is wrong (e.g. only mmx register but no sse register)
- the rewritten instruction is wrong (e.g. fild which is used in std.math)
- code is duplicated for 32bit and 64bit mode

If you want to have a look at it: source is in `gen/asmstmts.cpp`, `gen/asm-x64-32.h` and `gen/asm-x64-64.h`

**Comment by dnadlinger** [comment]
> code is duplicated for 32bit and 64bit mode

Yep, this is a real problem. Any larger amount of work on the inline asm support should probably start with merging the two implementations together (I think GDC also had them merged before inline asm was removed altogether, might be worth to compare).

**Comment by kinke** [comment]
Okay thanks. I merged the two assembly parsers, see https://github.com/ldc-developers/ldc/pull/273. I used meld for a side-by-side diff of the original parsers and implemented the diffs. The affected parts have also been cosmetically fixed. After that, I did a double and triple check by side-by-side diff'ing between the new merged parser and each original parser.

**Pull request closed without merging**
