### PR TITLE
fix issue 3127 - increase stack size of mark threads to 64 kB

### PR DESCRIPTION
**Pull request by rainers**

### CODE REVIEW

**Comment by rainers** [comment]
@kinke Can you try whether this resolves the CircleCI issue?

**Comment by kinke** [comment]
Thx, I'll try later when at home. @dnadlinger mentioned that only glibc (IIRC) puts a thread's TLS area into the stack, so I'd propose increasing the stack size only for `version (CRuntime_Glibc)`, and probably not using a problematic hardcoded size, but make it depend on the spawning thread's total TLS size.

**Comment by dnadlinger** [comment]
My statement was meant the other way round – it's a glibc implementation detail that the TLS area is at the top of the stack, which it might or might not share with other platforms. Off the top of my head, macOS/FreeBSD are indeed different, but it's been a while.

**Comment by rainers** [comment]
> , and probably not using a problematic hardcoded size, but make it depend on the spawning thread's total TLS size.

Yeah, I meant this as a test only. It actually seems to be the problem, see https://github.com/dlang/dub/issues/1812#issuecomment-573129889

**Comment by kinke** [comment]
Confirmed, it fixes the CircleCI issues as well as the 2 Travis Linux shared-libs jobs, which have been failing almost every time since a couple of weeks ago.

**Comment by kinke** [comment]
The [upstream fix](https://github.com/dlang/druntime/pull/2904) is in `ldc-merge-2090` already, closing.

**Pull request closed without merging**
