### PR TITLE
WIP: wasi support

### PR DESCRIPTION
**Pull request by skoppe**
Need this to try out my clone of azure pipelines.

### CODE REVIEW

**Comment by skoppe** [comment]
Nvmd, apparently it doesn't work like that. I got another solution though.

**Comment by thewilsonator** [comment]
Please target these upstream if possible.

**Comment by skoppe** [comment]
I will, but I first want to get the ldc CI working.

**Comment by thewilsonator** [comment]
OK.

**Comment by kinke** [comment]
> I will, but I first want to get the ldc CI working.

Then you don't need the druntime/Phobos PRs here, because there's no CI. ;) - You can instead open an LDC PR and change the submodule repo URLs to your forks to have them tested.

**Comment by skoppe** [comment]
My reasoning was that if I opened a PR for the relevant commits of phobos/druntime, they would be in their respective ldc repos, so that the azure pipeline of my clone of ldc would be able to find those commits and I wouldn't have to update the submodule repo URLs.

Alas, it doesn't work like that. Plus updating the submodule repo URLs is pretty simple. TIL.

I have got the CI to compile so I can open up a ldc PR. Will do later today when time allows.

**Pull request closed without merging**
