### PR TITLE
Integrate backtrace refactoring and fixes for libunwind

### PR DESCRIPTION
**Pull request by Geod24**
This cherry-picks commits from the following PRs, in order:
- https://github.com/dlang/druntime/pull/3322
- https://github.com/dlang/druntime/pull/3323
- https://github.com/dlang/druntime/pull/3321
- https://github.com/dlang/druntime/pull/3328 ~(not merged yet)~
- https://github.com/dlang/druntime/pull/3329
- https://github.com/dlang/druntime/pull/3331

### CODE REVIEW

**Comment by kinke** [comment]
Thanks! Had to follow-up with a little fixup:
```diff
diff --git a/src/core/internal/backtrace/dwarf.d b/src/core/internal/backtrace/dwarf.d
index 76d5b4d3..4775c61b 100644
--- a/src/core/internal/backtrace/dwarf.d
+++ b/src/core/internal/backtrace/dwarf.d
@@ -52,6 +52,13 @@ module core.internal.backtrace.dwarf;
 import core.internal.execinfo;
 import core.internal.string;

+version (DRuntime_Use_Libunwind)
+    private enum hasLibunwind = true;
+else
+    private enum hasLibunwind = false;
+
+static if (hasExecinfo || hasLibunwind):
+
 version (OSX)
     version = Darwin;
 else version (iOS)
@@ -165,6 +172,9 @@ static if (hasExecinfo)
         import core.stdc.stdio : snprintf;
         import core.sys.posix.stdlib : free;

+        const char** frameList = backtrace_symbols(callstack.ptr, cast(int) callstack.length);
+        scope(exit) free(cast(void*) frameList);
+
         auto image = Image.openSelf();

         // find address -> file, line mapping using dwarf debug_line
diff --git a/src/core/internal/backtrace/libunwind.d b/src/core/internal/backtrace/libunwind.d
index fff25bb1..b0fd6ec2 100644
--- a/src/core/internal/backtrace/libunwind.d
+++ b/src/core/internal/backtrace/libunwind.d
@@ -181,6 +181,7 @@ else version (AArch64)

         version (linux)
         {
+            import core.stdc.config : c_ulong;
             import core.sys.posix.signal : sigset_t, stack_t;

             // libunwind has some special tweaking to reduce
@@ -226,6 +227,8 @@ else version (ARM)
     }
     else
     {
+        import core.stdc.config : c_ulong;
+
         struct unw_tdep_context_t
         {
             c_ulong[16] regs;
```

There are still compile errors for Android wrt. missing `ucontext_t` which could presumably be worked around with a `version = DRuntime_Use_LLVM_Libunwind` for Android (the NDK comes with a `libunwind.a`); no idea whether that's a good idea.

Should the compiler predefine `DRuntime_Use_Libunwind` for musl targets etc.? Otherwise the druntime user might not get what he asks for with a prebuilt druntime compiled with a manual `version`...

**Edit**: Oh and does the C compiler need an explicit `-lunwind` or so with `DRuntime_Use_Libunwind`, or is that one of the automagic libs?

**Comment by Geod24** [comment]
> Should the compiler predefine `DRuntime_Use_Libunwind` for musl targets etc.? Otherwise the druntime user might not get what he asks for with a prebuilt druntime compiled with a manual version...

I was planning on patching it in the package until it's fully tested and upstreamed, but that works too. [For reference, this is what I have for DMD](https://gitlab.alpinelinux.org/alpine/aports/-/blob/30733b5583b0294a0ebc295dbb493c7c62cff274/community/dmd/10-dmd-musl.patch) (it's using the old implementation, before I dropped non-LLVM libunwind). But since Alpine is the main (only?) target for Musl at the moment, might as well do it in LDC.

> which could presumably be worked around with a `version = DRuntime_Use_LLVM_Libunwind`

`version = DRuntime_Use_Libunwind`. I dropped support for the actual libunwind.

> Edit: Oh and does the C compiler need an explicit `-lunwind` or so with `DRuntime_Use_Libunwind`, or is that one of the automagic libs?

I don't know. But since I'm patching the config file anyway, I can take care of that when I update the packages.

**Comment by kinke** [comment]
> I dropped support for the actual libunwind.

So what's the `DRuntime_Use_LLVM_Libunwind` in `libunwind.d`?

**Comment by Geod24** [comment]
> So what's the `DRuntime_Use_LLVM_Libunwind` in `libunwind.d`?

Cherry picked from the wrong branch 🤦 
Fixed now, and integrated your diff.

~EDIT: Actually just found a small bug, hold on.~

Fixed: I needed to add the skip code in `traceHandlerOpApply2` too.

**Comment by kinke** [comment]
Okay, I've pushed 2 new commits.

**Comment by Geod24** [comment]
@kinke : Thanks! Anything else you need from my side ? Are you interested in upstreaming the additional commits ?

**Comment by kinke** [comment]
> Are you interested in upstreaming the additional commits ?

I'll do it at one point unless you're keen on cherry-picking it yourself. ;)

> Anything else you need from my side ?

I'm now predefining the version and linking`-lunwind` for musl targets in https://github.com/ldc-developers/ldc/pull/3641 - could you please test & verify it for a smooth v1.25.0 on Alpine?

**Pull request merged**
