### PR TITLE
WinEH: fix double exception handling with UCRT lib 10.0.14393.0

### PR DESCRIPTION
**Pull request by rainers**
This should fix the AppVeyor failures.

### CODE REVIEW

**Comment by rainers** [comment]
Amended a better fix. What was the procedure to test druntime changes as PRs to LDC?

**Comment by dnadlinger** [comment]
Just push them to the ldc-developers repo (as a branch if you want), and put up a `ldc` PR. Not ideal, unfortunately.

**Comment by rainers** [comment]
Thanks, tried it here https://github.com/ldc-developers/ldc/pull/1706

**Comment by rainers** [comment]
Seems to be working, merging into ldc branch...

**Pull request merged**
