### PR TITLE
posix.termios: add Solaris.

### PR DESCRIPTION
**Pull request by nykytenko**
Tested on Solaris like OS.

### CODE REVIEW

**Comment by kinke** [comment]
Thx for all your Solaris fixes. Are you targeting the ldc branch from now on or will you continue to make sure ltsmaster supports Solaris properly too?

**Comment by nykytenko** [comment]
> Are you targeting the ldc branch from now

Yes

We needed ltsmaster only for first building LDC on new platform (SmartOS x64). Next, we will work with ldc branch.

**Comment by kinke** [comment]
Alright, then I'll just trust you and merge this.
How does LDC fare on Solaris/SmartOS? Does it pass all unittests and dmd-testsuite?

**Comment by nykytenko** [comment]
Thank, kinke.

> Does it pass all unittests and dmd-testsuite?

Some tests failed now.
I and Alexandr Basko working on it.
See:
https://forum.dlang.org/thread/emkoxgqykzqdqzikiriv@forum.dlang.org?page=3

**Pull request merged**
