### PR TITLE
Add interface for inline IR.

### PR DESCRIPTION
**Pull request by redstar**
Like the __asm template: this is an __ir template.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
~~~Perhaps rename to __llvm?  (not sure if I would recognize "__ir" in code... although on second thought, the string passed to __ir will look an awful lot like LLVM IR ;-)~~~
I vote __ir.

**Comment by 9il** [comment]
LGTM

**Comment by JohanEngelen** [comment]
@redstar  After merging this, could you add a simple test for it in tests/ir ? 

Edit: there is a test for the pragma in dmd-testsuite/runnable/ldc_llvm_inline_ir.  Could you update that test to use this new interface?

**Comment by JohanEngelen** [comment]
Also, ldc/simd.di should be updated to use this interface.

**Comment by JohanEngelen** [comment]
@redstar Let's get this in? :-)

**Comment by redstar** [comment]
I am a bit slow on this. Before merging I like to update `ldc.simd` and `core.thread`. And for sure, the test need an update, too. :-)

**Comment by redstar** [comment]
I am a bit slow on this. Before merging I like to update `ldc.simd` and `core.thread`. And for sure, the test need an update, too. :-)

**Comment by JohanEngelen** [comment]
@redstar Just saw this PR again. Still want to get this in?

**Comment by JohanEngelen** [comment]
added here: https://github.com/ldc-developers/druntime/pull/149

**Pull request closed without merging**
