### PR TITLE
Modify automatically-generated linker section delimiter symbol names for LDC

### PR DESCRIPTION
**Pull request by joakim-noah**
This was in the upstream druntime pull, but since it's specific to LDC, put it here instead.

### CODE REVIEW

**Comment by dnadlinger** [comment]
Probably fine.

**Review by dnadlinger — APPROVED** [review]

**Comment by dnadlinger** [comment]
(I wonder whether we should just unify the section names between DMD and LDC instead.)

**Comment by kinke** [comment]
I was just thinking the same. Always good to decrease the diff wrt. upstream, and it's not like those 2 additional underscores would provide any value. ;)

**Comment by joakim-noah** [comment]
Either approach would be fine by me.

**Comment by kinke** [comment]
[No need for immediate action. ;)]

**Pull request merged**
