### PR TITLE
[ltsmaster] Implement vararg functions for MIPS32.

### PR DESCRIPTION
**Pull request by redstar**
This needs to go to master, too.

### CODE REVIEW

**Comment by redstar** [comment]
@rracariu You might be interested in this PR.

**Comment by rracariu** [comment]
Copied your changes and gave it a try with `ldc2 -mtriple=mipsel-unknown-linux-uclibc -mcpu=mips32r2 -gcc=mipsel-openwrt-linux-uclibc-gcc`

```
import core.stdc.stdarg;

extern (C) int test(int a, ...)
{
    va_list args;
    va_start(args, a);

    int i;
    va_arg(args, i);
    return i;
}
```
I got a segmentation fault in LDC:
```
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2a)[0x7fd2e463beea]
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x3e)[0x7fd2e463a06e]
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(+0x7fa1bc)[0x7fd2e463a1bc]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fd2e3c31390]
~/dlang/ldc/bin/ldc2(_ZNK10IrFunction11getLLVMFuncEv+0x0)[0x823db0]
~/dlang/ldc/bin/ldc2(_Z17DtoDefineFunctionP15FuncDeclarationb+0x132)[0x7b6b22]
~/dlang/ldc/bin/ldc2(_ZN15FuncDeclaration6acceptEP7Visitor+0x1d)[0x6a1e89]
~/dlang/ldc/bin/ldc2[0x7abed3]
~/dlang/ldc/bin/ldc2(_ZN16TemplateInstance6acceptEP7Visitor+0x1d)[0x658e39]
~/dlang/ldc/bin/ldc2(_Z19Declaration_codegenP7DsymbolP7IRState+0x34)[0x7af3c4]
~/dlang/ldc/bin/ldc2(_Z13codegenModuleP7IRStateP6Module+0xc5)[0x7cd2e5]
~/dlang/ldc/bin/ldc2(_ZN3ldc13CodeGenerator4emitEP6Module+0xa1)[0x86f871]
~/dlang/ldc/bin/ldc2(_Z14codegenModulesR5ArrayIP6ModuleE+0x18c)[0x84547c]
~/dlang/ldc/bin/ldc2(_Z13mars_mainBodyR5ArrayIPKcES3_+0x274c)[0x6f6dfc]
~/dlang/ldc/bin/ldc2(_Z7cppmainiPPc+0x1bc5)[0x843215]
~/dlang/ldc/bin/ldc2(_Dmain+0x26)[0x79b2ba]
~/dlang/ldc/bin/ldc2(_D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv+0x28)[0x885a74]
~/dlang/ldc/bin/ldc2(_D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFNlMDFZvZv+0x20)[0x8859a4]
~/dlang/ldc/bin/ldc2(_D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFNlZv+0x2d)[0x885a1d]
~/dlang/ldc/bin/ldc2(_D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFNlMDFZvZv+0x20)[0x8859a4]
~/dlang/ldc/bin/ldc2(_d_run_main+0x1b4)[0x885914]
~/dlang/ldc/bin/ldc2(main+0x10)[0x79b2d0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fd2e2da0830]
~/dlang/ldc/bin/ldc2(_start+0x29)[0x58f109]
```
LDC version:
```
LDC - the LLVM D compiler (1.7.0):
  based on DMD v2.077.1 and LLVM 5.0.0
  built with DMD64 D Compiler v2.074.0
  Default target: x86_64-pc-linux-gnu
  Host CPU: broadwell
```

**Comment by redstar** [comment]
:-) I am not sure if the implementation is 100% correct, but it should not crash ldc.

**Comment by rracariu** [comment]
BTW, this causes the crash: `va_arg(args, i);`

**Comment by rracariu** [comment]
@redstar scratch that :) I gave it another try and the problem was that I didn't updated the file in `ldc/import`... 

The test runs on real hardware 👍

**Comment by redstar** [comment]
@rracariu The example works on my hardware, too (MIPS Creator CI20 with native ldc2 0.17.6).

**Pull request merged**
