### PR TITLE
adjust Win EH terminate hook to newer vcruntime versions

### PR DESCRIPTION
**Pull request by rainers**
Not sure what update to the VC runtime broke this. All 3 different versions on my system don't work anymore.

### CODE REVIEW

**Comment by kinke** [comment]
I've tested `runnable\eh.d` with this (with and without `-O3`). VS 2015 Update 3 works fine now with all 4 variants, thanks, but VS 2017 (14.10.25017) only works with `libcmt` and fails with the other 3. Using WinSDK 10.0.15063 for both VS 2015 and VS 2017.

**Comment by rainers** [comment]
vcruntime and vcruntimed 14.10.25017 seem to work here, too. I'm testing it by just putting these into the build_results/runnable folder, though.

The ucrt libraries are also involved, so what version of ucrtbase.dll and ucrtbased.dll are you using? Unfortunately, these are not so easily replacable in the executable folder.

**Comment by rainers** [comment]
> Using WinSDK 10.0.15063

Ok, I'm on version 10.0.14393.0. If the newer version works with VS2015, that part of the stack should be ok, though.

**Comment by kinke** [comment]
Oh and I forgot to mention that I only tested Win64, no 32-bit tests yet.

**Comment by rainers** [comment]
I have updated my desktop computer to Windows 10.0.15063, so it now picks up ucrtbase.dll with that version. I cannot reproduce crashes running `eh.d` with `-mscrtlib=msvcrt` with different vcruntime versions. Using the debug runtime still picks up another version of ucrtbased.dll, though.

Edit: after updating the WinSDK, ucrtbased.dll 10.0.15063 is loaded and works, too.

**Comment by kinke** [comment]
Did you relink every time or just replace the DLLs? I relinked, i.e., I used `-mscrtlib={libcmt[d],msvcrt[d]}` each in a VS2015 and VS2017 x64 command prompt.

**Comment by kinke** [comment]
Okay, I upgraded Windows yesterday too, and now it's working (again no 32-bit tests - did you happen to test those too?). So apparently there are some Windows/WinSDK/VS/C-runtime-variant combos which we don't support.

**Comment by rainers** [comment]
I tried 32-bit VS2017 with ucrt 10.0.14393 recently, and that seemd to be ok.

**Comment by rainers** [comment]
> Did you relink every time or just replace the DLLs?

The latest tests were compiled against VS2015 and exchanged DLLs (no VS2017 on the desktop yet), but earlier tests were compiled against VS2017.

**Pull request merged**
