### PR TITLE
Llvm15 intrinsics

### PR DESCRIPTION
**Pull request by thewilsonator**
I can't really remember how submodule PRs work, but this is the diff needed to compile druntime with LLVM15 (added LDC_LLVM_1600 to minimise the number of druntime PRs)

### CODE REVIEW

**Comment by kinke** [comment]
Well, you're almost there. :)
* The branch must be on our repo and derived from our current `ldc` head. Check.
* To use and test it from an LDC PR, just commit the druntime bump in that PR.
* Once the LDC PR is merged, merge the druntime branch into the `ldc` branch too and then remove the branch. This should always be a fast-forward merge, i.e., `ldc` mustn't have been touched in the meantime.

[After adapting to the DMD+druntime monorepo, we'll only have a single Phobos submodule, and this workflow will hardly ever be needed anymore.]

**Comment by thewilsonator** [comment]
> To use and test it from an LDC PR,

Done.

> merge the druntime branch into the ldc branch too and then remove the branch.

I don't quite get this. You mean merge this PR (into the `ldc` branch of druntime)? I don't get what you mean by "remove the branch".

**Comment by kinke** [comment]
> You mean merge this PR (into the ldc branch of druntime)?

Well, I'm not sure about the GitHub UI merge here, I've (always?) merged+pushed manually.

> I don't get what you mean by "remove the branch".

https://github.com/ldc-developers/druntime/branches

**Comment by thewilsonator** [comment]
Yes I just noticed that this PR branch is on `ldc-developers` not on my fork.

**Comment by kinke** [comment]
Which is fine and a prerequisite as mentioned in point 1 above.

**Comment by thewilsonator** [comment]
Ah crap, there were two commits that when squashed changed hash.

**Comment by kinke** [comment]
That's why I mentioned manual merging. - Now needs another LDC commit to fix up the druntime submodule, pointing to latest `ldc`.

**Comment by thewilsonator** [comment]
rebase wasn't an option for ldc's druntime, says it was disabled.

**Comment by thewilsonator** [comment]
https://github.com/ldc-developers/ldc/pull/4173

**Pull request merged**
