### PR TITLE
Check fiber migrations on iOS derived platforms

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Comment by kinke** [comment]
Thx, will merge soon. - What's the current state of AArch64/iOS with LDC master? druntime/Phobos unittests all green? Just asking for the v1.21.0-beta1 release notes...

**Comment by jacob-carlborg** [comment]
> hat's the current state of AArch64/iOS with LDC master? druntime/Phobos unittests all green? Just asking for the v1.21.0-beta1 release notes...

All unit tests pass, at least last time I tried, a couple of days ago.

**Comment by jacob-carlborg** [comment]
I had to make few additional changes in Phobos, which have been merged now [1]. They don’t affect the unit tests. 

[1] https://github.com/dlang/phobos/pull/7422

**Comment by kinke** [comment]
Excellent, thanks!

**Comment by jacob-carlborg** [comment]
> Just asking for the v1.21.0-beta1 release notes...

Has https://github.com/dlang/phobos/pull/7355 been merged into LDC?

**Comment by kinke** [comment]
I assumed so according to your statement above, but as it apparently missed 2.091, it isn't.

**Comment by jacob-carlborg** [comment]
> I assumed so according to your statement above, but as it apparently missed 2.091, it isn't.

Yes, I can see how my comment was confusing, that's my fault. What I did was to update my branch to latest LDC master and then applied https://github.com/dlang/phobos/pull/7355. No new changes or additions were required. I guess we'll have to wait for the next release.

**Comment by kinke** [comment]
Hmm, that means about 3 months until it's available in a non-beta release. I'm tempted to cherry-pick it eagerly...

**Comment by jacob-carlborg** [comment]
> I'm tempted to cherry-pick it eagerly...

I wouldn't mind 😃.

**Pull request merged**
