### PR TITLE
Remove double definition

### PR DESCRIPTION
**Pull request by rracariu**
Version block was doubled. Merge issue probably.

### CODE REVIEW

**Comment by kinke** [comment]
Thx [and there might be more].

**Comment by kinke** [comment]
As to your forum post, your stuff should all be in there AFAICT; if something got mixed up, it did so without merge conflicts. Let's try to make it work for 1.9 final, that's what betas are for.

**Comment by rracariu** [comment]
Looks that most of the uClibc changes in the beta are from before the 2.0.79 release. There are lots of PRs after that that are missing for the merge. The list is quite big, I manually merged back on my local setup most of the stuff from mainline in order to get it to compile.

Thanks for looking into this, I would definitely like to have this in 1.9

**Comment by kinke** [comment]
> Looks that most of the uClibc changes in the beta are from before the 2.0.79 release. There are lots of PRs after that that are missing for the merge. The list is quite big, I manually merged back on my local setup most of the stuff from mainline in order to get it to compile.

Just to be clear, LDC 1.9 contains **everything** from the 2.079.1 DMD release. Looks like you opened upstream PRs after that, which will only make it into 2.080 (hopefully, beta1 out already). Cherry-picking all of them is not what we'd usually do, in order to simplify future merges (and to avoid artifacts such as this duplicate block here). So I'm not sure backporting is the way to go here.

**Comment by rracariu** [comment]
OK, that's what I was afraid. No worries, just that you will need to pull out mentions of the uClibc support, people might try it out to find out that it doesn't work.

**Pull request merged**
