### PR TITLE
Solaris: fix readdir for x64 OS.

### PR DESCRIPTION
**Pull request by nykytenko**
Patch by @nykytenko, originally submitted at dlang#1566.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@nykytenko the purpose of LTS master is to be able to build lastest LDC (which requires a D compiler). Are these patches needed for that?
If not, I think you should make the PRs for druntime/master instead. We don't want to spread our time and energy too much on maintaining LTS, and rather spend it on master. But in this case, I think you don't need a PR at all: your patches to DMD/druntime will eventually make it into LDC/druntime automatically, because we merge DMD/druntime into LDC/druntime from time to time.

**Comment by nykytenko** [comment]
We need these patches in both ldc/druntime branches: LTS master and master. LTS master use for first build LDC on different Solaris(illumos) distros. For next steps we need master branch. Without these patches LDC is not built on x64 Solaris OS.

> your patches to DMD/druntime will eventually make it into LDC/druntime automatically, because we merge DMD/druntime into LDC/druntime from time to time.

Patched LTS master we need now, patched master is not urgently for us.

**Comment by JohanEngelen** [comment]
OK, thanks for letting me know. I'll merge them then :)

**Comment by nykytenko** [comment]
Thank, Johan.

**Comment by JohanEngelen** [comment]
Does LDC ltsmaster build now, or are there still some remaining issues?

**Comment by nykytenko** [comment]
Need last patch to ldc/phobos ltsmaster ( originally submitted at: Solaris: corrected getcwd call. #4276 ). After merge this patch LDC ltsmaster will be built.
You may cherry-pick this comment from dlang/phobos/master to ldc-developers/phobos/ldc-ltsmaster. Or I may to make pull request with this comment.

**Comment by redstar** [comment]
Normally we cherry-pick such changes from upstream. But we have no established process for this. (In the past, the upstream changes were created by LDC developers. In this case it is easy to know which commit to cherry-pick.)

**Comment by nykytenko** [comment]
How do I make? You cherry-pick dlang/phobos/master pull request #4276 to ldc-developers/phobos/ldc-ltsmaster or I need to do pull request?

**Pull request merged**
