### PR TITLE
Solaris: add utsname.

### PR DESCRIPTION
**Pull request by nykytenko**

### CODE REVIEW

**Comment by dnadlinger** [comment]
Thanks for the patch!

Unfortunately, I had forgotten that the Solaris support pieces are also in upstream (DMD's) druntime, so I'll submit them there first and cherry-pick the patch back once it has been merged there.

**Comment by dnadlinger** [comment]
Upstream PR: https://github.com/dlang/druntime/pull/1551

You (@nykytenko) don't really need to do anything, I'll make sure it is merged upstream and trickles down into LDC.

**Comment by nykytenko** [comment]
Thank, klickverbot.
Where i should add next druntime patch, in upstream (DMD's) druntime or in this ldc fork?

**Comment by dnadlinger** [comment]
In general, we try to directly upstream everything that is applicable, as it makes merging in new frontend releases easier. Even if we might want to cherry-pick certain changes (e.g. platform support ones), being able to reference an upstream commit id makes making sense of merge conflicts much easier later on.

**Pull request merged**
