### PR TITLE
Moved src/ldc/simd.d to import/ldc/simd.di

### PR DESCRIPTION
**Pull request by jkrempus**

### CODE REVIEW

**Comment by dnadlinger** [comment]
Actually, it should be the other way round – we should move our .di files from `import` to src, as this has been done in upstream as well. I guess you aren't keen on doing some CMake work? ;)

**Comment by jkrempus** [comment]
I can do that. So files from import/ldc/ need to be moved to src/ldc/ and CMake files need to be changed so that they install them from there?

**Comment by dnadlinger** [comment]
@jerro: Thanks, that would be great. Yes, the files have to be moved, and if both a .d and a .di file are present (e.g. for core.thread), the .di one has to be copied to the import/ working directory instead of generating it with `-H`.

**Comment by dnadlinger** [comment]
And maybe you might be able to fix https://github.com/ldc-developers/ldc/issues/207 while you are at it.

**Comment by dnadlinger** [comment]
Just closing this one now; let's continue any discussions at the main issue tracker.

**Pull request closed without merging**
