### PR TITLE
Fix link issue with uClibc

### PR DESCRIPTION
**Pull request by rracariu**
Use the intrinsic for `rndtol` on uClibc

### CODE REVIEW

**Comment by kinke** [comment]
For uClibc support, please target branch `ldc-merge-2.079` (submodules) / `merge-2.079` (main LDC repo), as that already contains all the other upstream uClibc stuff and should thus be much better suited for checking LDC compatibility.
[[2.079](https://github.com/ldc-developers/ldc/pull/2587) is basically already working fine on Windows and Linux. dmd-testsuite is expected to fail, as are the 32-bit std.file unittests with enabled optimizations (Linux only).]

**Comment by kinke** [comment]
Btw I don't think this works, I'd expect a linking error when trying to use `core.math.rndtol()`.

**Comment by rracariu** [comment]
Without the versioned block:, when building druntime test runner
```
~/ldc-build-runtime.tmp/lib/libdruntime-ldc-unittest-debug.a(math.o): In function `_D4core4math6rndtolFNaNbNiNfeZl':
~/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/math.d:83: undefined reference to `llroundl'
collect2: error: ld returned 1 exit status
```

**Comment by kinke** [comment]
They apparently cheat and use the double version for `long double`: https://github.com/kraj/uClibc/blob/master/libm/ldouble_wrappers.c#L275
So better do the same here in druntime (but in `core.stdc.math`, like for Android/Bionic [here](https://github.com/ldc-developers/druntime/blob/ldc-merge-2.079/src/core/stdc/math.d#L3977)) instead of declaring an unimplemented `rndtol()` (only hiding the linking error as there are no unittests).

**Comment by rracariu** [comment]
OK, thanks for looking into it!

I did the right thing TM and pushed this https://github.com/dlang/druntime/pull/2132

**Pull request closed without merging**
