### PR TITLE
[WIP] Implement stdarg on AArch64.

### PR DESCRIPTION
**Pull request by redstar**

### CODE REVIEW

**Comment by redstar** [comment]
@smolt Please, could you check that the new `object.d` does not interfere with your work on iOS? Thanks!

**Comment by smolt** [comment]
Thanks for the heads up, but It won't interfere.   iOS arm64 calling convention is a variation on AAPCS64 and uses the simpler va_list as a char*.  There is no concept of __va_list_tag.

For reference: https://github.com/smolt/druntime/blob/ios-merge-ldc/src/core/stdc/stdarg.d#L358

**Comment by smolt** [comment]
It turns out that something similar is needed for arm AAPCS because it typedefs `va_list` as `std::__va_list` and affects C++ mangling.  For now I have `extern (C++,std) struct __va_list {void *__ap;}` in core/stdc.stdarg.d.  Should it end up in object.d too?

**Comment by redstar** [comment]
@smolt Nice - I found this, too. Yes, it should also end up in object.d.

**Comment by redstar** [comment]
See #63 for version against lts-master.

**Pull request closed without merging**
