### PR TITLE
Merge Thread class upstream changes

### PR DESCRIPTION
**Pull request by denizzzka**
Merge changes what was introduced in upstream PR https://github.com/dlang/druntime/pull/3135

### CODE REVIEW

**Comment by denizzzka** [comment]
<s>not checked yet</s>

**Comment by denizzzka** [comment]
Looks good, but ./ldc-build-runtime.tmp/phobos2-test-runner-debug test fail.

I think this is not related to this PR (it fails also on release branch)

This fail occured because `std.stdio` unittest calls `exit(0)` what causes call of modules shared dtors:
```D
        // Since locks are per-process, we cannot test lock failures within
        // the same process. fork() is used to create a second process.
        static void runForked(void delegate() code)
        {
            import core.stdc.stdlib : exit;
            import core.sys.posix.sys.wait : waitpid;
            import core.sys.posix.unistd : fork;
            int child, status;
            if ((child = fork()) == 0)
            {
                code();
                exit(0); // here
            }
            else
            {
                assert(waitpid(child, &status, 0) != -1);
                assert(status == 0, "Fork crashed");
            }
        }
```
```
0.005s PASS debug64 std.regex.internal.parser
0.309s PASS debug64 std.regex.internal.tests
0.046s PASS debug64 std.regex.internal.tests2
0.008s PASS debug64 std.regex
0.000s PASS debug64 std.signals
1.954s PASS debug64 std.socket
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPSQCk3sys5posix6signal9siginfo_tPvZv+0x4c)[0x558c1b0fa85c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x13520)[0x7f7265d0c520]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xa357)[0x7f7265d03357]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D4core6thread8osthread6Thread4joinMFbZC6object9Throwable+0x28)[0x558c1b0ff028]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D3std11parallelism26_sharedStaticDtor_L1048_C1FZ14__foreachbody1MFKC4core6thread8osthread6ThreadZi+0x73)[0x558c19e95db3]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D4core6thread8osthread6Thread7opApplyFMDFKCQBqQBoQBkQBeZiZi+0x5d)[0x558c1b0ffbdd]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D3std11parallelism26_sharedStaticDtor_L1048_C1FZv+0x14)[0x558c19e95d34]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt5minfo__T17runModuleFuncsRevSQBgQBg11ModuleGroup8runDtorsMFZ9__lambda1ZQCkMFAxPyS6object10ModuleInfoZv+0x67)[0x558c1b121627]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt5minfo11ModuleGroup8runDtorsMFZv+0x21)[0x558c1b1215b1]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt19sections_elf_shared20runModuleDestructorsFPSQBxQBx3DSObZv+0x3e)[0x558c1b12490e]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_d_dso_registry+0x40f)[0x558c1b12468f]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(+0x1d4f91e)[0x558c1820191e]
/lib64/ld-linux-x86-64.so.2(+0xf943)[0x7f7265eaf943]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c600)[0x7f7265b4b600]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c73a)[0x7f7265b4b73a]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D3std5stdio4File20__unittest_L1571_C13FZ9runForkedFDFZvZv+0x3d)[0x558c1a91fb9d]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D3std5stdio4File20__unittest_L1571_C13FZv+0x6c)[0x558c1a91fa3c]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(+0x44e4a82)[0x558c1a996a82]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D11test_runner6doTestFPS6object10ModuleInfoKS4core7runtime14UnitTestResultZv+0x6e)[0x558c182015ee]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D11test_runner7testAllFZ14__foreachbody1MFPS6object10ModuleInfoZi+0x15)[0x558c18201775]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D6object10ModuleInfo7opApplyFMDFPSQBhQBdZiZ9__lambda2MFyPSQCfQCbZi+0x19)[0x558c1b10a289]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt5minfo17moduleinfos_applyFMDFyPS6object10ModuleInfoZiZ14__foreachbody2MFKSQCz19sections_elf_shared3DSOZi+0x56)[0x558c1b1218c6]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt19sections_elf_shared3DSO7opApplyFMDFKSQBqQBqQyZiZi+0x55)[0x558c1b123a85]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt5minfo17moduleinfos_applyFMDFyPS6object10ModuleInfoZiZi+0x30)[0x558c1b121840]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D6object10ModuleInfo7opApplyFMDFPSQBhQBdZiZi+0x28)[0x558c1b1088b8]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D11test_runner7testAllFZS4core7runtime14UnitTestResult+0x3d)[0x558c1820154d]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D11test_runner6testerFZS4core7runtime14UnitTestResult+0x3a)[0x558c1820131a]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(runModuleUnitTests+0xd1)[0x558c1b0fa431]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt6dmain212_d_run_main2UAAamPUQgZiZ6runAllMFZv+0x23)[0x558c1b1155d3]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_D2rt6dmain212_d_run_main2UAAamPUQgZiZ7tryExecMFMDFZvZv+0x23)[0x558c1b115553]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_d_run_main2+0x33a)[0x558c1b11540a]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_d_run_main+0x104)[0x558c1b1150c4]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(main+0x25)[0x558c18201895]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7f7265b35bbb]
./ldc-build-runtime.tmp/phobos2-test-runner-debug(_start+0x2a)[0x558c1820107a]
****** FAIL debug64 std.stdio
core.exception.AssertError@std/stdio.d(1593): Fork crashed
----------------
exception.d:447 onAssertErrorMsg [0x558c1b0f5f97]
exception.d:590 _d_assert_msg [0x558c1b0f63e5]
stdio.d:1593 void std.stdio.File.__unittest_L1571_C13().runForked(void delegate()) [0x558c1a91fbdc]
stdio.d:1599 void std.stdio.File.__unittest_L1571_C13() [0x558c1a91fa3b]
stdio.d:0 [0x558c1a996a81]
test_runner.d:73 void test_runner.doTest(object.ModuleInfo*, ref core.runtime.UnitTestResult) [0x558c182015ed]
test_runner.d:57 int test_runner.testAll().__foreachbody1(object.ModuleInfo*) [0x558c18201774]
object.d:1854 int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*)) [0x558c1b10a288]
minfo.d:777 int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x558c1b1218c5]
sections_elf_shared.d:93 int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x558c1b123a84]
minfo.d:770 int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))) [0x558c1b12183f]
object.d:1853 int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)) [0x558c1b1088b7]
test_runner.d:55 core.runtime.UnitTestResult test_runner.testAll() [0x558c1820154c]
test_runner.d:25 core.runtime.UnitTestResult test_runner.tester() [0x558c18201319]
runtime.d:598 runModuleUnitTests [0x558c1b0fa430]
dmain2.d:559 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x558c1b1155d2]
dmain2.d:533 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x558c1b115552]
dmain2.d:592 _d_run_main2 [0x558c1b115409]
dmain2.d:386 _d_run_main [0x558c1b1150c3]
/home/denizzz/Dev/tt2/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/internal/entrypoint.d:42 main [0x558c18201894]
??:? __libc_start_main [0x7f7265b35bba]
??:? _start [0x558c18201079]
0.022s PASS debug64 std.string
0.004s PASS debug64 std.traits
0.006s PASS debug64 std.typecons
0.000s PASS debug64 std.typetuple
0.388s PASS debug64 std.uni
0.512s PASS debug64 std.uri
```

So, this PR can be merged?

**Comment by denizzzka** [comment]
Try to fix std.stdio unittest: https://github.com/dlang/phobos/pull/7543

**Comment by kinke** [comment]
> So, this PR can be merged?

The upstream change will land in 2.094, and cherry-picking this eagerly seems not worth it, as it's only a preparational refactoring for a bigger refactoring as I understand.

Have there been any tedious merge conflicts? In that case, this PR might make merging 2.094 easier.

**Comment by denizzzka** [comment]
> The upstream change will land in 2.094, and cherry-picking this eagerly seems not worth it,

Sure!

> as it's only a preparational refactoring for a bigger refactoring as I understand.

Don't know about all changes, but this PR contains all Thread stuff what changed in upstream for now.

> Have there been any tedious merge conflicts?

Oh, yeah!
I made this PR to simplify merging because I still remember what changed in core.thread.

**Comment by denizzzka** [comment]
> as it's only a preparational refactoring for a bigger refactoring as I understand.

Just bad naming of this git branch

**Comment by denizzzka** [comment]
> Try to fix std.stdio unittest: dlang/phobos#7543

I closed this PR

Looks like this is specific for LDC "bug/feature" of working with modules

**Comment by kinke** [comment]
The refactoring was regularly merged into branch `ldc-merge-2.094`, making this obsolete. Thanks anyway!

**Pull request closed without merging**
