### PR TITLE
MIPS32: Fix another assembly warning.

### PR DESCRIPTION
**Pull request by rracariu**
(cherry picked from commit 92977be98098719dcdf2d02e9d0ed502d2ad0d63)

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@rracariu It's better to target these fixes to the `ldc` branch, instead of the `ldc-merge-2.079` branch (unless impossible), because otherwise we get a mixed bag of changes instead of a more clear "these are all the changes that come with updating to 2.079".

**Comment by rracariu** [comment]
A while ago was advised by @kinke to target the current `ldc-merge-xx` branch for my changes. It's confusing now, which branch is actually the main branch?

BTW One of the commits is cherry picked from `ldc-ltsmaster`

**Comment by JohanEngelen** [comment]
`ldc` is the main branch.

Other MIPS32 changes were already pulled onto merge-2.079, so that's not helping. Using a proper incremental development style now would be cumbersome for you, so it's ok. Let's keep it in mind in the future.

**Comment by JohanEngelen** [comment]
@redstar

**Comment by kinke** [comment]
FWIW, I referred to ldc-merge-2.079 then because those were uClibc changes, which has only landed upstream in 2.079. I don't care which branch you target, ldc-merge-2.079 should be merged into ldc very soon anyway.

**Comment by rracariu** [comment]
OK, I will push to `ldc` for future work. There are some PRs to push trough upstream for uClibc MIPS32 so it is in better shape.

Do you have a schedule when you plan to beta the next version of LDC? The major MIPS32 showstopper atm is a seg fault in the fiber `switch_context` asm block, I would like to get this sorted and have the rest of the upstream PR in before that.

Thanks!

**Comment by dnadlinger** [comment]
(Don't worry too much about branches for runtime PRs, by the way, as what counts is updating the tag in the main repository anyway. What matters is only mergeability, that is, make it obvious that changes are meant for an upcoming frontend version branch if they require something from that version, and just work off of whatever the submodule in `ldc/master` points to otherwise. The latter _should_ be `ldc`, but sometimes it gets desynced.)

**Pull request merged**
