### PR TITLE
Add support for atomicFetchAdd and atomicFetchSub

### PR DESCRIPTION
**Pull request by rymrg**
Add support for atomicFetchAdd and atomicFetchSub.

https://dlang.org/phobos/core_atomic.html#.atomicFetchAdd
https://dlang.org/phobos/core_atomic.html#.atomicFetchSub

### CODE REVIEW

**Comment by kinke** [comment]
Oh I didn't realize there are public wrappers in `core.atomic` now (apparently untested...); IIRC, they started out as helper functions in `core.internal.atomic` for `core.atomic.atomicOp()`, where LDC doesn't need them, so I left them out back then.

**Comment by rymrg** [comment]
You're right. If I don't use a self built version they don't work. How can I help in adding this for next version? Atomic variables cannot be implemented without this.
```D
/usr/include/dlang/ldc/core/internal/atomic.d(32,28): Error: llvm_atomic_store cannot be interpreted at compile time, because it has no available source code
```

**Comment by kinke** [comment]
> How can I help in adding this for next version?

This PR should suffice; please fix the indentation, add an empty line inbetween both new functions, and move them after `atomicStore` as for the DMD block.

> Atomic variables cannot be implemented without this.

`atomicOp!"+="` and `atomicOp!"-="` don't work? They are tested.

While looking at the upstream code, I've noticed a copy-paste error - `atomicFetchSub` for pointers using `atomicFetchAdd`: https://github.com/dlang/druntime/blob/13e358e253e6a420dcfc83244c9479f2db6e8178/src/core/atomic.d#L199
It'd be great if you could fix that upstream too.

**Comment by rymrg** [comment]
Done. I'm not sure how I got the error message from earlier as I cannot reproduce it right now (it was with atomicStore which is required for atomic assignment).
For reference, I also fixed the upstream issue [dlang/druntime/pull/3342].

**Comment by kinke** [comment]
Thx!

**Pull request merged**
